AWSTemplateFormatVersion : '2010-09-09'
Parameters: 
  DomainName: 
    Type: String
    Default: 'jongardner.ca'
  HostedZoneId: 
    Type: String
    Default: 'Z2N1DMFEX4I0PO'
Resources:

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Jon-Portfolio Website'

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames: 
        - !Sub "www.${DomainName}"
      ValidationMethod: DNS

  PortfolioS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName

  PortfolioS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PortfolioS3Bucket
      PolicyDocument:
      # Restricting access to cloudfront only.
        Statement:
          -
            Effect: Allow
            Action: 's3:GetObject'
            Resource:
              - !Sub "arn:aws:s3:::${PortfolioS3Bucket}/*"
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - PortfolioS3Bucket
    Properties:
      DistributionConfig:
        Comment: Jon-Portfolio
        Origins:
        - Id: S3Origin
          DomainName: !GetAtt PortfolioS3Bucket.DomainName
          S3OriginConfig:
              # Restricting Bucket access through an origin access identity
              OriginAccessIdentity: 
                Fn::Sub: 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
          - !Sub "${DomainName}"
          - !Sub "www.${DomainName}"
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
          - ErrorCode: '403'
            ResponsePagePath: "/"
            ResponseCode: '200'
            ErrorCachingMinTTL: '300'
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only